"""empty message

Revision ID: 37860ec38ebb
Revises: 21ff12f42af2
Create Date: 2022-11-08 08:45:06.048647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37860ec38ebb'
down_revision = '21ff12f42af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('retailer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'retailer')
    op.drop_column('items', 'private')
    # ### end Alembic commands ###
